# Generated by Django 3.2.8 on 2023-11-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('menu_title', models.CharField(max_length=1000, verbose_name='Название в меню')),
                ('section_title', models.CharField(max_length=1000, verbose_name='Название раздела')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('first_phone', models.CharField(blank=True, max_length=1000, verbose_name='Телефон #1')),
                ('second_phone', models.CharField(blank=True, max_length=1000, verbose_name='Телефон #2')),
                ('email', models.CharField(max_length=1000, verbose_name='Email')),
                ('telegram', models.CharField(max_length=1000, verbose_name='Telegram')),
                ('whatsapp', models.CharField(max_length=1000, verbose_name='Whatsapp')),
            ],
            options={
                'verbose_name': 'Общая страница',
                'verbose_name_plural': 'Общая страница',
            },
        ),
    ]
