# Generated by Django 3.2.8 on 2023-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='header_phone',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Телефон в шапке сайта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Whatsapp'),
        ),
    ]
