# Generated by Django 3.2.8 on 2023-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_requisites_requisites_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisites_items',
            options={'ordering': ['order'], 'verbose_name': 'Реквизит', 'verbose_name_plural': 'Реквизиты'},
        ),
        migrations.AddField(
            model_name='requisites_items',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
