# Generated by Django 3.2.8 on 2023-11-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20231126_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='menu_title',
            new_name='menu_name',
        ),
    ]
