# Generated by Django 3.2.8 on 2023-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_rename_menu_title_contacts_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Заголовок'),
        ),
    ]
