# Generated by Django 3.2.8 on 2023-12-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20231213_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='subtitle',
            field=models.TextField(verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='requisites_items',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='requisites_items',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Заголовок'),
        ),
    ]
