# Generated by Django 3.2.8 on 2024-04-02 04:19

import astra.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20231213_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='form_file',
            field=models.FileField(default=1, help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to=astra.functions.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл персональных данных'),
            preserve_default=False,
        ),
    ]
