# Generated by Django 3.2.8 on 2025-05-28 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contacts_form_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='form_file',
        ),
        migrations.AddField(
            model_name='contacts',
            name='first_file',
            field=models.FileField(default=1, help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл - "Согласие на обработку персональных данных"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='fourth_file',
            field=models.FileField(default=1, help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл - "Согласие на обработку персональных данных, собираемых метрическими системами"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='second_file',
            field=models.FileField(default=1, help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл - "Положение по работе с персональными данными"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='third_file',
            field=models.FileField(default=1, help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл - "Политика использования файлов cookies"'),
            preserve_default=False,
        ),
    ]
