# Generated by Django 3.2.8 on 2025-05-28 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20250528_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='first_file',
            field=models.FileField(help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='fourth_file',
            field=models.FileField(help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Согласие на обработку персональных данных, собираемых метрическими системами'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='second_file',
            field=models.FileField(help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Положение по работе с персональными данными'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='third_file',
            field=models.FileField(help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Политика использования файлов cookies'),
        ),
    ]
