# Generated by Django 3.2.8 on 2023-11-20 06:46

import astra.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('main_title', models.TextField(verbose_name='Заголовок на баннере')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Общая страница',
                'verbose_name_plural': 'Общая страница',
            },
        ),
        migrations.CreateModel(
            name='main_page_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_items', to='main.main_page')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
    ]
