# Generated by Django 3.2.8 on 2023-11-28 01:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_main_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_page',
            name='main_title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок на видео'),
        ),
    ]
