# Generated by Django 3.2.8 on 2023-11-19 23:52

import astra.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20231120_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='manufacturer_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('menu_name', models.CharField(max_length=1000, verbose_name='Название в меню')),
                ('section_title', models.CharField(max_length=1000, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Общая страница',
                'verbose_name_plural': 'Общая страница',
            },
        ),
        migrations.CreateModel(
            name='manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_categories', to='products.categories', verbose_name='Выбрать категорию')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_country', to='manufacturers.country', verbose_name='Выбрать страну')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['order'],
            },
        ),
    ]
