# Generated by Django 3.2.8 on 2023-11-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='show_about',
            field=models.BooleanField(default=False, verbose_name='Отображать на странице "О нас"'),
        ),
    ]
