# Generated by Django 3.2.8 on 2023-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_manufacturers_show_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='man_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория производителей',
                'verbose_name_plural': 'Категории производителей',
            },
        ),
    ]
