# Generated by Django 3.2.8 on 2023-11-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20231126_2116'),
        ('manufacturers', '0003_man_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='man_categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_page_categories', to='products.categories', verbose_name='Выбрать категорию'),
            preserve_default=False,
        ),
    ]
