# Generated by Django 3.2.8 on 2023-11-26 18:47

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0004_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='image_png',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='image_png2x',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
            preserve_default=False,
        ),
    ]
