# Generated by Django 3.2.8 on 2023-11-26 18:52

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0005_auto_20231126_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='image_png',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='image_png2x',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
        ),
    ]
