# Generated by Django 3.2.8 on 2023-11-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20231126_2116'),
        ('manufacturers', '0006_auto_20231126_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='man_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_categories', to='products.categories', verbose_name='Выбрать категорию на главной странице'),
        ),
    ]
