# Generated by Django 3.2.8 on 2023-11-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0007_alter_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='man_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_categories', to='manufacturers.man_categories', verbose_name='Выбрать категорию на главной странице'),
        ),
    ]
