# Generated by Django 3.2.8 on 2023-11-27 23:46

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0008_alter_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='image_about',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
        ),
    ]
