# Generated by Django 3.2.8 on 2023-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0009_manufacturers_image_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование производителя'),
        ),
    ]
