# Generated by Django 3.2.8 on 2023-12-12 17:59

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0010_manufacturers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='image',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
