# Generated by Django 3.2.8 on 2023-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_subcategories_image'),
        ('manufacturers', '0011_alter_manufacturers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='categories',
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='categories',
            field=models.ManyToManyField(related_name='manufacturer_categories', to='products.categories', verbose_name='Выбрать категорию'),
        ),
    ]
