# Generated by Django 3.2.8 on 2023-12-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0012_auto_20231212_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка'),
        ),
    ]
