# Generated by Django 3.2.8 on 2023-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0013_manufacturers_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок'),
        ),
    ]
