# Generated by Django 3.2.8 on 2023-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_subcategories_image'),
        ('manufacturers', '0015_alter_manufacturers_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='manufacturer_categories', to='products.categories', verbose_name='Выбрать категорию'),
        ),
    ]
