# Generated by Django 3.2.8 on 2023-12-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_subcategories_image'),
        ('manufacturers', '0016_alter_manufacturers_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='categories',
            field=models.ManyToManyField(related_name='manufacturer_categories', to='products.categories', verbose_name='Выбрать категорию'),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='man_categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_page_categories', to='manufacturers.man_categories', verbose_name='Выбрать категорию на главной странице'),
        ),
    ]
