# Generated by Django 3.2.8 on 2023-12-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0017_auto_20231212_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='man_categories',
        ),
    ]
