# Generated by Django 3.2.8 on 2023-12-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0018_remove_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='man_categories',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_page_categories', to='manufacturers.man_categories', verbose_name='Выбрать категорию на главной странице'),
            preserve_default=False,
        ),
    ]
