# Generated by Django 3.2.8 on 2023-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0019_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
