# Generated by Django 3.2.8 on 2023-12-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0020_alter_manufacturers_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='man_categories',
        ),
    ]
