# Generated by Django 3.2.8 on 2023-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0022_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка'),
        ),
    ]
