# Generated by Django 3.2.8 on 2023-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0023_alter_manufacturers_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка'),
        ),
    ]
