# Generated by Django 3.2.8 on 2023-12-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0024_alter_manufacturers_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='man_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_page_categories', to='manufacturers.man_categories', verbose_name='Выбрать категорию на главной странице'),
        ),
    ]
