# Generated by Django 3.2.8 on 2023-12-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0025_alter_manufacturers_man_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='man_categories',
        ),
    ]
