# Generated by Django 3.2.8 on 2024-03-31 16:37

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0027_manufacturers_man_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='image_about',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='image_png',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='image_png2x',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
    ]
