# Generated by Django 3.2.8 on 2023-11-20 06:12

import astra.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Партнер компании',
                'verbose_name_plural': 'Партнеры компании',
            },
        ),
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('menu_name', models.CharField(max_length=1000, verbose_name='Название в меню')),
                ('section_title', models.CharField(max_length=1000, verbose_name='Название раздела')),
                ('first_subtitle', models.TextField(blank=True, verbose_name='Верхний подзаголовок')),
                ('second_subtitle', models.TextField(blank=True, verbose_name='Нижний подзаголовок')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Общая страница',
                'verbose_name_plural': 'Общая страница',
            },
        ),
        migrations.CreateModel(
            name='about_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Принципы компании',
                'verbose_name_plural': 'Принципы компании',
            },
        ),
        migrations.CreateModel(
            name='about_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'География поставок',
                'verbose_name_plural': 'География поставок',
            },
        ),
        migrations.CreateModel(
            name='about_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='about_team_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('position', models.CharField(max_length=1000, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
                ('about_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_team_items', to='about.about_team')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='about_supplies_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('count', models.CharField(max_length=1000, verbose_name='Количество')),
                ('title', models.CharField(max_length=1000, verbose_name='Описание')),
                ('about_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_supplies_items', to='about.about_supplies')),
            ],
            options={
                'verbose_name': 'География поставок',
                'verbose_name_plural': 'География поставок',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='about_rules_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('about_rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_rules_items', to='about.about_rules')),
            ],
            options={
                'verbose_name': 'Принцип компании',
                'verbose_name_plural': 'Принципы компании',
                'ordering': ['order'],
            },
        ),
    ]
