# Generated by Django 3.2.8 on 2023-11-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_page',
            name='image',
        ),
    ]
