# Generated by Django 3.2.8 on 2023-11-26 11:46

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_team_items',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='about_team_items',
            name='image',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
