# Generated by Django 3.2.8 on 2023-11-28 00:20

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20231126_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_team_items',
            name='image_png',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='about_team_items',
            name='image_png2x',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path),
        ),
    ]
