# Generated by Django 3.2.8 on 2023-11-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20231128_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_team_items',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
