# Generated by Django 3.2.8 on 2024-03-31 16:36

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_team_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_team_items',
            name='image_png',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AlterField(
            model_name='about_team_items',
            name='image_png2x',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
    ]
