# Generated by Django 3.2.8 on 2023-11-19 23:32

import astra.functions
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('menu_name', models.CharField(max_length=1000, verbose_name='Название в меню')),
                ('section_title', models.CharField(max_length=1000, verbose_name='Название раздела')),
                ('main_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Общая страница каталога',
                'verbose_name_plural': 'Общая страница каталога',
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=1000, verbose_name='Наименование категории')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='subcategory_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Общая страница подкатегории',
                'verbose_name_plural': 'Общая страница подкатегорий',
            },
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=1000, verbose_name='Наименование подкатегории')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
                ('icon', models.FileField(help_text='Формат файла: SVG. Ограничени размера: 500 Кбайт.', upload_to=astra.functions.get_file_path, verbose_name='Иконка')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.categories', verbose_name='Выбрать категорию')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['order'],
            },
        ),
    ]
