# Generated by Django 3.2.8 on 2023-11-19 23:44

import astra.functions
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_title',
            field=models.CharField(default=1, max_length=1000, verbose_name='Наименование подкатегории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('show', models.BooleanField(blank=True, default=True, verbose_name='Показывать на сайте')),
                ('leftovers', models.BooleanField(blank=True, default=True, verbose_name='Складские остатки')),
                ('pop_models', models.BooleanField(blank=True, default=True, verbose_name='Популярные модели')),
                ('product_title', models.CharField(max_length=1000, verbose_name='Наименование продукта')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
                ('subcategories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_subcategory', to='products.subcategories', verbose_name='Выбрать подкатегорию')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['order'],
            },
        ),
    ]
