# Generated by Django 3.2.8 on 2023-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231120_0244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subcategory_page',
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_title',
            field=models.CharField(default=1, max_length=1000, verbose_name='Наименование категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='categories',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
    ]
