# Generated by Django 3.2.8 on 2023-11-26 13:02

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231126_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image_2x_jpg',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_2x_webp',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_jpg',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_webp',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL'),
        ),
    ]
