# Generated by Django 3.2.8 on 2023-11-26 14:48

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231126_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='image_2x_jpg',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='image_2x_webp',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='image_jpg',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='image_webp',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path),
        ),
    ]
