# Generated by Django 3.2.8 on 2023-11-26 15:44

import astra.functions
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_subcategories_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show',
        ),
        migrations.AddField(
            model_name='product',
            name='image_detail_png',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_detail_png2x',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_detail_webp',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_other_png',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_other_png2x',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_other_webp',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=1000, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
