# Generated by Django 3.2.8 on 2023-11-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20231126_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=1000, verbose_name='Параметр')),
                ('subtitle', models.CharField(max_length=1000, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='products.product')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['order'],
            },
        ),
    ]
