# Generated by Django 3.2.8 on 2023-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=1, verbose_name='Стоимость продукта за 1 шт'),
        ),
    ]
