# Generated by Django 3.2.8 on 2023-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_char_title',
            field=models.CharField(default=1, max_length=1000, verbose_name='Заголовок характеристик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Заголовок описания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(blank=True, default=1, verbose_name='Стоимость продукта за 1 шт'),
        ),
    ]
