# Generated by Django 3.2.8 on 2023-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_chars',
            name='title',
            field=models.TextField(verbose_name='Характеристика'),
        ),
    ]
