# Generated by Django 3.2.8 on 2023-11-26 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_chars_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_chars',
            name='subtitle',
            field=ckeditor.fields.RichTextField(verbose_name='Значение'),
        ),
    ]
