# Generated by Django 3.2.8 on 2023-11-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_char_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_title',
        ),
    ]
