# Generated by Django 3.2.8 on 2023-12-12 14:12

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20231126_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
