# Generated by Django 3.2.8 on 2024-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0027_manufacturers_man_categories'),
        ('products', '0020_alter_product_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='manufacturers',
            field=models.ManyToManyField(related_name='subcategories_manufacturers', to='manufacturers.manufacturers', verbose_name='Выбрать производителей'),
        ),
    ]
