# Generated by Django 3.2.8 on 2024-03-31 16:38

import astra.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_subcategories_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_detail_png',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_detail_png2x',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_detail_webp',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_other_png',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_other_png2x',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_other_webp',
            field=models.ImageField(blank=True, upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
