# Generated by Django 3.2.8 on 2025-08-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_brands_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ['-brand_title'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['-country_title'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default=1, max_length=1000, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_brands', to='products.brands', verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_country', to='products.countries', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
