# Generated by Django 3.2.8 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20250822_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.BooleanField(blank=True, default=True, verbose_name='В наличии'),
        ),
    ]
