# Generated by Django 3.2.8 on 2025-08-25 03:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_page',
            name='seo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст для SEO'),
        ),
        migrations.AddField(
            model_name='categories',
            name='seo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст для SEO'),
        ),
    ]
