# Generated by Django 3.2.8 on 2025-08-25 05:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20250825_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('question', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
                ('catalog_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_catalog_page', to='products.catalog_page')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_categories', to='products.categories')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
    ]
