# Generated by Django 3.2.8 on 2025-08-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='catalog_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_catalog_page', to='products.catalog_page'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_categories', to='products.categories'),
        ),
    ]
