# Generated by Django 3.2.8 on 2025-08-25 06:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20250825_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст для SEO'),
        ),
    ]
