# Generated by Django 3.2.8 on 2025-08-25 07:23

import astra.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение')),
                ('alt', models.CharField(max_length=500, verbose_name='alt-тег')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_slider', to='products.product')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
    ]
