# Generated by Django 3.2.8 on 2025-08-25 07:29

import astra.functions
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_page',
            name='dostavka',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Оплата и доставка'),
        ),
        migrations.CreateModel(
            name='product_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('file', models.FileField(help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to=astra.functions.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Документ')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_file', to='products.product')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order'],
            },
        ),
    ]
