# Generated by Django 3.2.8 on 2025-09-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20250825_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Стоимость продукта за 1 шт'),
        ),
    ]
