# Generated by Django 3.2.8 on 2025-09-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_title', models.CharField(max_length=1000, verbose_name='Наименование бренда')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
                'ordering': ['-filter_title'],
            },
        ),
        migrations.CreateModel(
            name='filters_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_title', models.CharField(max_length=1000, verbose_name='Значение')),
                ('filters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters_parameters', to='products.filters')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
                'ordering': ['-parameter_title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, to='products.filters_parameters', verbose_name='Значения фильтров'),
        ),
    ]
