# Generated by Django 3.2.8 on 2025-09-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20250902_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filters',
            options={'ordering': ['filter_title'], 'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
        migrations.AlterModelOptions(
            name='filters_parameters',
            options={'ordering': ['parameter_title'], 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='products_filters', to='products.filters_parameters', verbose_name='Значения фильтров'),
        ),
    ]
