# Generated by Django 3.2.8 on 2025-09-05 09:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20250902_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq_subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('question', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_subcategories', to='products.subcategories')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
    ]
