# Generated by Django 3.2.8 on 2025-09-05 09:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_faq_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='seo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст для SEO'),
        ),
    ]
