# Generated by Django 3.2.8 on 2025-11-14 10:09

import astra.functions
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0028_auto_20240331_1937'),
        ('products', '0037_subcategories_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование бренда'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование бренда'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование бренда'),
        ),
        migrations.AlterField(
            model_name='filters_parameters',
            name='parameter_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brands', to='products.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='countries',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_country', to='products.countries', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product_chars',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product_chars',
            name='title',
            field=models.TextField(blank=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='product_file',
            name='file',
            field=models.FileField(blank=True, help_text='Формат файла: PDF. Ограничение размера: 20 Мбайт.', upload_to=astra.functions.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='product_file',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product_parameters',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product_parameters',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='product_slider',
            name='alt',
            field=models.CharField(blank=True, max_length=500, verbose_name='alt-тег'),
        ),
        migrations.AlterField(
            model_name='product_slider',
            name='image',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=astra.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='icon',
            field=models.FileField(blank=True, help_text='Формат файла: SVG. Ограничени размера: 500 Кбайт.', upload_to=astra.functions.get_file_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, related_name='subcategories_manufacturers', to='manufacturers.manufacturers', verbose_name='Выбрать производителей'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Заголовок'),
        ),
    ]
